services:

  mongodb:

    image: mongo:7.0

    container_name: mongodb

    restart: unless-stopped

    environment:

      MONGO_INITDB_ROOT_USERNAME: dbadmin

      MONGO_INITDB_ROOT_PASSWORD: "Admin123"

    volumes:

      - mongo_data:/data/db

      - ./backend/data/seed.sh:/docker-entrypoint-initdb.d/seed.sh:ro

      - ./backend/data/sample_posts.json:/docker-entrypoint-initdb.d/sample_posts.json:ro

    networks:

      - wanderlust-network



  redis:

    image: redis:7.0.5-alpine

    container_name: redis

    restart: unless-stopped

    command: redis-server --appendonly yes

    volumes:

      - redis_data:/data

    networks:

      - wanderlust-network



  backend:

    image: kbsingh10/wanderlust-backend:latest

    container_name: backend

    restart: unless-stopped

    env_file:

      - ./backend/.env.sample 

    ports:

      - "5000:5000"

    depends_on:

      - mongodb

      - redis

    networks:

      - wanderlust-network



  frontend:

    image: kbsingh10/wanderlust-frontend:latest

    container_name: frontend

    restart: unless-stopped

    ports:

      - "80:80"

    depends_on:

      - backend

    networks:

      - wanderlust-network



volumes:

  mongo_data:

  redis_data:



networks:

  wanderlust-network:

    driver: bridge